[package]
name = "tfhe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-bigint = "0.5.5"
fast-ntt = { git = "https://github.com/0xWOLAND/fast-ntt/" }
num-bigfloat = "1.7.0"
